// - Arquivos = Rotas
// No Next.js, cada arquivo page.tsx dentro da pasta app é uma rota. O arquivo app/page.tsx é a rota / e o arquivo app/sobre/page.tsx é a rota /sobre.

// basicamente para criar rotas com next é muuito mais fácil. basta criar uma pasta dentro de app com o nome da rota, ex: 'sobre' e dentro dessa pasta adicionar um arquivo chamado page.tsx, isso já vai fazer com que o next indentifique aquele arquivo como uma rota.

// Obs: É bom criar um arquivo chamado components dentro da pasta src para não confundir os components com as rotas e depois importar o componente desejado direto dessa pasta.

// Dica: para importar algo, o next indentifica a raiz da pasta src com um @, o que facilita para importar, porque ao invés de ter que procurar as pastas por ex: ../../x, basta usar @/ que já está falando com a pasta src, ou seja, para importar o componente nesse caso seria @/components/sobre

// app/page.tsx
// o nome do componente não importa, apenas o nome do arquivo
export default function HomePage() {
  return (
    <main>
      <h1>Home</h1>
    </main>
  );
}

// app/sobre/page.tsx
export default function SobrePage() {
  return (
    <main>
      <h1>Sobre</h1>
    </main>
  );
}
//obs: o de cima é a mesma coisa que fazer usando o rafce:
// exporta a função da mesma forma porém é mais fácil de criar com o rafce

import React from "react";

const SobrePage2 = () => {
  return <div></div>;
};

export default SobrePage2;

//------------------------------------------------------------------------------------

// - layout.tsx
// O arquivo layout.tsx é o layout padrão de todas as páginas. Ele é importado automaticamente pelo Next.js e pode ser usado para adicionar elementos que se repetem em todas as páginas, como a navegação ou footer por exemplo.

// Na raiz ele é necessário para adicionar o <html> e o <body>. Porém nas demais rotas ele é opcional.

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}

//------------------------------------------------------------------------------------
// - metadata
// Exportar um objeto const metadata, irá adicionar as meta tags na página. Pode ser exportado de qualquer arquivo de rota, como page.tsx ou layout.tsx.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// se não definir a metadata, o next vai usar a metadata principal do layout

//------------------------------------------------------------------------------------

// - App Router e Pages Router
// Existe também um sistema de rotas chamado Pages Router, que era o padrão do Next.js antes da versão 13. Hoje em dia é recomendado usar o App Router.
